// Auto-generated by fetch-data.js — do not edit manually
// Last updated: 2026-06-15T11:03:00.961Z
window.LIVE_DATA = {
  "fetchedAt": "2026-06-15T11:03:00.961Z",
  "eliminated": [],
  "groupStandings": {
    "Group A": [
      {
        "team": "Mexico",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 2,
        "ga": 0,
        "gd": 2,
        "points": 3
      },
      {
        "team": "Korea Republic",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 2,
        "ga": 1,
        "gd": 1,
        "points": 3
      },
      {
        "team": "Czechia",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 1,
        "ga": 2,
        "gd": -1,
        "points": 0
      },
      {
        "team": "South Africa",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 0,
        "ga": 2,
        "gd": -2,
        "points": 0
      }
    ],
    "Group B": [
      {
        "team": "Switzerland",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Canada",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Qatar",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Bosnia and Herzegovina",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      }
    ],
    "Group C": [
      {
        "team": "Scotland",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 1,
        "ga": 0,
        "gd": 1,
        "points": 3
      },
      {
        "team": "Morocco",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Brazil",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 1,
        "ga": 1,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Haiti",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 0,
        "ga": 1,
        "gd": -1,
        "points": 0
      }
    ],
    "Group D": [
      {
        "team": "USA",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 4,
        "ga": 1,
        "gd": 3,
        "points": 3
      },
      {
        "team": "Australia",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 2,
        "ga": 0,
        "gd": 2,
        "points": 3
      },
      {
        "team": "Türkiye",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 0,
        "ga": 2,
        "gd": -2,
        "points": 0
      },
      {
        "team": "Paraguay",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 1,
        "ga": 4,
        "gd": -3,
        "points": 0
      }
    ],
    "Group E": [
      {
        "team": "Germany",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 7,
        "ga": 1,
        "gd": 6,
        "points": 3
      },
      {
        "team": "Côte d'Ivoire",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 1,
        "ga": 0,
        "gd": 1,
        "points": 3
      },
      {
        "team": "Ecuador",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 0,
        "ga": 1,
        "gd": -1,
        "points": 0
      },
      {
        "team": "Curaçao",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 1,
        "ga": 7,
        "gd": -6,
        "points": 0
      }
    ],
    "Group F": [
      {
        "team": "Sweden",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "gf": 5,
        "ga": 1,
        "gd": 4,
        "points": 3
      },
      {
        "team": "Japan",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Netherlands",
        "played": 1,
        "won": 0,
        "drawn": 1,
        "lost": 0,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 1
      },
      {
        "team": "Tunisia",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "gf": 1,
        "ga": 5,
        "gd": -4,
        "points": 0
      }
    ],
    "Group G": [
      {
        "team": "Egypt",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Belgium",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "IR Iran",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "New Zealand",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ],
    "Group H": [
      {
        "team": "Cabo Verde",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Saudi Arabia",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Spain",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Uruguay",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ],
    "Group I": [
      {
        "team": "France",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Iraq",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Norway",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Senegal",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ],
    "Group J": [
      {
        "team": "Algeria",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Argentina",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Jordan",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Austria",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ],
    "Group K": [
      {
        "team": "Congo DR",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Colombia",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Portugal",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Uzbekistan",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ],
    "Group L": [
      {
        "team": "England",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Ghana",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Croatia",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      },
      {
        "team": "Panama",
        "played": 0,
        "won": 0,
        "drawn": 0,
        "lost": 0,
        "gf": 0,
        "ga": 0,
        "gd": 0,
        "points": 0
      }
    ]
  },
  "groupMatches": {
    "A": [
      {
        "home": "Mexico",
        "away": "South Africa",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-11T19:00:00Z"
      },
      {
        "home": "Korea Republic",
        "away": "Czechia",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-12T02:00:00Z"
      },
      {
        "home": "Czechia",
        "away": "South Africa",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T16:00:00Z"
      },
      {
        "home": "Mexico",
        "away": "Korea Republic",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T01:00:00Z"
      },
      {
        "home": "Czechia",
        "away": "Mexico",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T01:00:00Z"
      },
      {
        "home": "South Africa",
        "away": "Korea Republic",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T01:00:00Z"
      }
    ],
    "B": [
      {
        "home": "Canada",
        "away": "Bosnia and Herzegovina",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-12T19:00:00Z"
      },
      {
        "home": "Qatar",
        "away": "Switzerland",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T19:00:00Z"
      },
      {
        "home": "Switzerland",
        "away": "Bosnia and Herzegovina",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T19:00:00Z"
      },
      {
        "home": "Canada",
        "away": "Qatar",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T22:00:00Z"
      },
      {
        "home": "Switzerland",
        "away": "Canada",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T19:00:00Z"
      },
      {
        "home": "Bosnia and Herzegovina",
        "away": "Qatar",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T19:00:00Z"
      }
    ],
    "D": [
      {
        "home": "USA",
        "away": "Paraguay",
        "homeScore": 4,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T01:00:00Z"
      },
      {
        "home": "Australia",
        "away": "Türkiye",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T04:00:00Z"
      },
      {
        "home": "USA",
        "away": "Australia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T19:00:00Z"
      },
      {
        "home": "Türkiye",
        "away": "Paraguay",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T03:00:00Z"
      },
      {
        "home": "Türkiye",
        "away": "USA",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T02:00:00Z"
      },
      {
        "home": "Paraguay",
        "away": "Australia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T02:00:00Z"
      }
    ],
    "C": [
      {
        "home": "Brazil",
        "away": "Morocco",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T22:00:00Z"
      },
      {
        "home": "Haiti",
        "away": "Scotland",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T01:00:00Z"
      },
      {
        "home": "Scotland",
        "away": "Morocco",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T22:00:00Z"
      },
      {
        "home": "Brazil",
        "away": "Haiti",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T00:30:00Z"
      },
      {
        "home": "Morocco",
        "away": "Haiti",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T22:00:00Z"
      },
      {
        "home": "Scotland",
        "away": "Brazil",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T22:00:00Z"
      }
    ],
    "E": [
      {
        "home": "Germany",
        "away": "Curaçao",
        "homeScore": 7,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T17:00:00Z"
      },
      {
        "home": "Côte d'Ivoire",
        "away": "Ecuador",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T23:00:00Z"
      },
      {
        "home": "Germany",
        "away": "Côte d'Ivoire",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T20:00:00Z"
      },
      {
        "home": "Ecuador",
        "away": "Curaçao",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T00:00:00Z"
      },
      {
        "home": "Ecuador",
        "away": "Germany",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T20:00:00Z"
      },
      {
        "home": "Curaçao",
        "away": "Côte d'Ivoire",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T20:00:00Z"
      }
    ],
    "F": [
      {
        "home": "Netherlands",
        "away": "Japan",
        "homeScore": 2,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T20:00:00Z"
      },
      {
        "home": "Sweden",
        "away": "Tunisia",
        "homeScore": 5,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T02:00:00Z"
      },
      {
        "home": "Netherlands",
        "away": "Sweden",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T17:00:00Z"
      },
      {
        "home": "Tunisia",
        "away": "Japan",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T04:00:00Z"
      },
      {
        "home": "Tunisia",
        "away": "Netherlands",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T23:00:00Z"
      },
      {
        "home": "Japan",
        "away": "Sweden",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T23:00:00Z"
      }
    ],
    "H": [
      {
        "home": "Spain",
        "away": "Cabo Verde",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T16:00:00Z"
      },
      {
        "home": "Saudi Arabia",
        "away": "Uruguay",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T22:00:00Z"
      },
      {
        "home": "Spain",
        "away": "Saudi Arabia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T16:00:00Z"
      },
      {
        "home": "Uruguay",
        "away": "Cabo Verde",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T22:00:00Z"
      },
      {
        "home": "Uruguay",
        "away": "Spain",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T00:00:00Z"
      },
      {
        "home": "Cabo Verde",
        "away": "Saudi Arabia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T00:00:00Z"
      }
    ],
    "G": [
      {
        "home": "Belgium",
        "away": "Egypt",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T19:00:00Z"
      },
      {
        "home": "IR Iran",
        "away": "New Zealand",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T01:00:00Z"
      },
      {
        "home": "Belgium",
        "away": "IR Iran",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T19:00:00Z"
      },
      {
        "home": "New Zealand",
        "away": "Egypt",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T01:00:00Z"
      },
      {
        "home": "New Zealand",
        "away": "Belgium",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T03:00:00Z"
      },
      {
        "home": "Egypt",
        "away": "IR Iran",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T03:00:00Z"
      }
    ],
    "I": [
      {
        "home": "France",
        "away": "Senegal",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T19:00:00Z"
      },
      {
        "home": "Iraq",
        "away": "Norway",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T22:00:00Z"
      },
      {
        "home": "France",
        "away": "Iraq",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T21:00:00Z"
      },
      {
        "home": "Norway",
        "away": "Senegal",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T00:00:00Z"
      },
      {
        "home": "Norway",
        "away": "France",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T19:00:00Z"
      },
      {
        "home": "Senegal",
        "away": "Iraq",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T19:00:00Z"
      }
    ],
    "J": [
      {
        "home": "Argentina",
        "away": "Algeria",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T01:00:00Z"
      },
      {
        "home": "Austria",
        "away": "Jordan",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T04:00:00Z"
      },
      {
        "home": "Argentina",
        "away": "Austria",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T17:00:00Z"
      },
      {
        "home": "Jordan",
        "away": "Algeria",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T03:00:00Z"
      },
      {
        "home": "Jordan",
        "away": "Argentina",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-28T02:00:00Z"
      },
      {
        "home": "Algeria",
        "away": "Austria",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-28T02:00:00Z"
      }
    ],
    "K": [
      {
        "home": "Portugal",
        "away": "Congo DR",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T17:00:00Z"
      },
      {
        "home": "Uzbekistan",
        "away": "Colombia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-18T02:00:00Z"
      },
      {
        "home": "Portugal",
        "away": "Uzbekistan",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T17:00:00Z"
      },
      {
        "home": "Colombia",
        "away": "Congo DR",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-24T02:00:00Z"
      },
      {
        "home": "Colombia",
        "away": "Portugal",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T23:30:00Z"
      },
      {
        "home": "Congo DR",
        "away": "Uzbekistan",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T23:30:00Z"
      }
    ],
    "L": [
      {
        "home": "England",
        "away": "Croatia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T20:00:00Z"
      },
      {
        "home": "Ghana",
        "away": "Panama",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T23:00:00Z"
      },
      {
        "home": "England",
        "away": "Ghana",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T20:00:00Z"
      },
      {
        "home": "Panama",
        "away": "Croatia",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T23:00:00Z"
      },
      {
        "home": "Panama",
        "away": "England",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T21:00:00Z"
      },
      {
        "home": "Croatia",
        "away": "Ghana",
        "homeScore": null,
        "awayScore": null,
        "status": "TIMED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T21:00:00Z"
      }
    ]
  },
  "knockoutMatches": {
    "r32": [],
    "r16": [],
    "qf": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-09T20:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-10T19:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-11T21:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-12T01:00:00Z"
      }
    ],
    "sf": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-14T19:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-15T19:00:00Z"
      }
    ],
    "final": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-19T19:00:00Z"
      }
    ]
  }
};
