// Auto-generated by fetch-data.js — do not edit manually
// Last updated: 2026-07-02T21:52:22.925Z
window.LIVE_DATA = {
  "fetchedAt": "2026-07-02T21:52:22.925Z",
  "eliminated": [
    "South Africa",
    "Japan",
    "Germany",
    "Netherlands",
    "Côte d'Ivoire",
    "Sweden",
    "Ecuador",
    "Congo DR",
    "Senegal",
    "Bosnia and Herzegovina",
    "Austria",
    "Czechia",
    "Qatar",
    "Türkiye",
    "Haiti",
    "Curaçao",
    "Tunisia",
    "Saudi Arabia",
    "New Zealand",
    "Iraq",
    "Jordan",
    "Uzbekistan",
    "Panama"
  ],
  "guaranteedQualified": [
    "Mexico",
    "South Africa",
    "Switzerland",
    "Canada",
    "Bosnia and Herzegovina",
    "USA",
    "Australia",
    "Paraguay",
    "Brazil",
    "Morocco",
    "Germany",
    "Côte d'Ivoire",
    "Netherlands",
    "Japan",
    "Spain",
    "Cabo Verde",
    "Belgium",
    "Egypt",
    "France",
    "Norway",
    "Argentina",
    "Austria",
    "Algeria",
    "Colombia",
    "Portugal",
    "England",
    "Croatia"
  ],
  "groupStandings": {
    "A": [
      {
        "team": "Mexico",
        "played": 3,
        "won": 3,
        "drawn": 0,
        "lost": 0,
        "gf": 6,
        "ga": 0,
        "gd": 6,
        "points": 9
      },
      {
        "team": "South Africa",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 2,
        "ga": 3,
        "gd": -1,
        "points": 4
      },
      {
        "team": "Korea Republic",
        "played": 3,
        "won": 1,
        "drawn": 0,
        "lost": 2,
        "gf": 2,
        "ga": 3,
        "gd": -1,
        "points": 3
      },
      {
        "team": "Czechia",
        "played": 3,
        "won": 0,
        "drawn": 1,
        "lost": 2,
        "gf": 2,
        "ga": 6,
        "gd": -4,
        "points": 1
      }
    ],
    "B": [
      {
        "team": "Switzerland",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 7,
        "ga": 3,
        "gd": 4,
        "points": 7
      },
      {
        "team": "Canada",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 8,
        "ga": 3,
        "gd": 5,
        "points": 4
      },
      {
        "team": "Bosnia and Herzegovina",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 5,
        "ga": 6,
        "gd": -1,
        "points": 4
      },
      {
        "team": "Qatar",
        "played": 3,
        "won": 0,
        "drawn": 1,
        "lost": 2,
        "gf": 2,
        "ga": 10,
        "gd": -8,
        "points": 1
      }
    ],
    "D": [
      {
        "team": "USA",
        "played": 3,
        "won": 2,
        "drawn": 0,
        "lost": 1,
        "gf": 8,
        "ga": 4,
        "gd": 4,
        "points": 6
      },
      {
        "team": "Australia",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 4
      },
      {
        "team": "Paraguay",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 2,
        "ga": 4,
        "gd": -2,
        "points": 4
      },
      {
        "team": "Türkiye",
        "played": 3,
        "won": 1,
        "drawn": 0,
        "lost": 2,
        "gf": 3,
        "ga": 5,
        "gd": -2,
        "points": 3
      }
    ],
    "C": [
      {
        "team": "Brazil",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 7,
        "ga": 1,
        "gd": 6,
        "points": 7
      },
      {
        "team": "Morocco",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 6,
        "ga": 3,
        "gd": 3,
        "points": 7
      },
      {
        "team": "Scotland",
        "played": 3,
        "won": 1,
        "drawn": 0,
        "lost": 2,
        "gf": 1,
        "ga": 4,
        "gd": -3,
        "points": 3
      },
      {
        "team": "Haiti",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 2,
        "ga": 8,
        "gd": -6,
        "points": 0
      }
    ],
    "E": [
      {
        "team": "Germany",
        "played": 3,
        "won": 2,
        "drawn": 0,
        "lost": 1,
        "gf": 10,
        "ga": 4,
        "gd": 6,
        "points": 6
      },
      {
        "team": "Côte d'Ivoire",
        "played": 3,
        "won": 2,
        "drawn": 0,
        "lost": 1,
        "gf": 4,
        "ga": 2,
        "gd": 2,
        "points": 6
      },
      {
        "team": "Ecuador",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 4
      },
      {
        "team": "Curaçao",
        "played": 3,
        "won": 0,
        "drawn": 1,
        "lost": 2,
        "gf": 1,
        "ga": 9,
        "gd": -8,
        "points": 1
      }
    ],
    "F": [
      {
        "team": "Netherlands",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 10,
        "ga": 4,
        "gd": 6,
        "points": 7
      },
      {
        "team": "Japan",
        "played": 3,
        "won": 1,
        "drawn": 2,
        "lost": 0,
        "gf": 7,
        "ga": 3,
        "gd": 4,
        "points": 5
      },
      {
        "team": "Sweden",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 7,
        "ga": 7,
        "gd": 0,
        "points": 4
      },
      {
        "team": "Tunisia",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 2,
        "ga": 12,
        "gd": -10,
        "points": 0
      }
    ],
    "H": [
      {
        "team": "Spain",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 5,
        "ga": 0,
        "gd": 5,
        "points": 7
      },
      {
        "team": "Cabo Verde",
        "played": 3,
        "won": 0,
        "drawn": 3,
        "lost": 0,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 3
      },
      {
        "team": "Uruguay",
        "played": 3,
        "won": 0,
        "drawn": 2,
        "lost": 1,
        "gf": 3,
        "ga": 4,
        "gd": -1,
        "points": 2
      },
      {
        "team": "Saudi Arabia",
        "played": 3,
        "won": 0,
        "drawn": 2,
        "lost": 1,
        "gf": 1,
        "ga": 5,
        "gd": -4,
        "points": 2
      }
    ],
    "G": [
      {
        "team": "Belgium",
        "played": 3,
        "won": 1,
        "drawn": 2,
        "lost": 0,
        "gf": 6,
        "ga": 2,
        "gd": 4,
        "points": 5
      },
      {
        "team": "Egypt",
        "played": 3,
        "won": 1,
        "drawn": 2,
        "lost": 0,
        "gf": 5,
        "ga": 3,
        "gd": 2,
        "points": 5
      },
      {
        "team": "IR Iran",
        "played": 3,
        "won": 0,
        "drawn": 3,
        "lost": 0,
        "gf": 3,
        "ga": 3,
        "gd": 0,
        "points": 3
      },
      {
        "team": "New Zealand",
        "played": 3,
        "won": 0,
        "drawn": 1,
        "lost": 2,
        "gf": 4,
        "ga": 10,
        "gd": -6,
        "points": 1
      }
    ],
    "I": [
      {
        "team": "France",
        "played": 3,
        "won": 3,
        "drawn": 0,
        "lost": 0,
        "gf": 10,
        "ga": 2,
        "gd": 8,
        "points": 9
      },
      {
        "team": "Norway",
        "played": 3,
        "won": 2,
        "drawn": 0,
        "lost": 1,
        "gf": 8,
        "ga": 7,
        "gd": 1,
        "points": 6
      },
      {
        "team": "Senegal",
        "played": 3,
        "won": 1,
        "drawn": 0,
        "lost": 2,
        "gf": 8,
        "ga": 6,
        "gd": 2,
        "points": 3
      },
      {
        "team": "Iraq",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 1,
        "ga": 12,
        "gd": -11,
        "points": 0
      }
    ],
    "J": [
      {
        "team": "Argentina",
        "played": 3,
        "won": 3,
        "drawn": 0,
        "lost": 0,
        "gf": 8,
        "ga": 1,
        "gd": 7,
        "points": 9
      },
      {
        "team": "Austria",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 6,
        "ga": 6,
        "gd": 0,
        "points": 4
      },
      {
        "team": "Algeria",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 5,
        "ga": 7,
        "gd": -2,
        "points": 4
      },
      {
        "team": "Jordan",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 3,
        "ga": 8,
        "gd": -5,
        "points": 0
      }
    ],
    "K": [
      {
        "team": "Colombia",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 4,
        "ga": 1,
        "gd": 3,
        "points": 7
      },
      {
        "team": "Portugal",
        "played": 3,
        "won": 1,
        "drawn": 2,
        "lost": 0,
        "gf": 6,
        "ga": 1,
        "gd": 5,
        "points": 5
      },
      {
        "team": "Congo DR",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 4,
        "ga": 3,
        "gd": 1,
        "points": 4
      },
      {
        "team": "Uzbekistan",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 2,
        "ga": 11,
        "gd": -9,
        "points": 0
      }
    ],
    "L": [
      {
        "team": "England",
        "played": 3,
        "won": 2,
        "drawn": 1,
        "lost": 0,
        "gf": 6,
        "ga": 2,
        "gd": 4,
        "points": 7
      },
      {
        "team": "Croatia",
        "played": 3,
        "won": 2,
        "drawn": 0,
        "lost": 1,
        "gf": 5,
        "ga": 5,
        "gd": 0,
        "points": 6
      },
      {
        "team": "Ghana",
        "played": 3,
        "won": 1,
        "drawn": 1,
        "lost": 1,
        "gf": 2,
        "ga": 2,
        "gd": 0,
        "points": 4
      },
      {
        "team": "Panama",
        "played": 3,
        "won": 0,
        "drawn": 0,
        "lost": 3,
        "gf": 0,
        "ga": 4,
        "gd": -4,
        "points": 0
      }
    ]
  },
  "groupMatches": {
    "A": [
      {
        "home": "Mexico",
        "away": "South Africa",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-11T19:00:00Z"
      },
      {
        "home": "Korea Republic",
        "away": "Czechia",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-12T02:00:00Z"
      },
      {
        "home": "Czechia",
        "away": "South Africa",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T16:00:00Z"
      },
      {
        "home": "Mexico",
        "away": "Korea Republic",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T01:00:00Z"
      },
      {
        "home": "Czechia",
        "away": "Mexico",
        "homeScore": 0,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T01:00:00Z"
      },
      {
        "home": "South Africa",
        "away": "Korea Republic",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T01:00:00Z"
      }
    ],
    "B": [
      {
        "home": "Canada",
        "away": "Bosnia and Herzegovina",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-12T19:00:00Z"
      },
      {
        "home": "Qatar",
        "away": "Switzerland",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T19:00:00Z"
      },
      {
        "home": "Switzerland",
        "away": "Bosnia and Herzegovina",
        "homeScore": 4,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T19:00:00Z"
      },
      {
        "home": "Canada",
        "away": "Qatar",
        "homeScore": 6,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-18T22:00:00Z"
      },
      {
        "home": "Switzerland",
        "away": "Canada",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T19:00:00Z"
      },
      {
        "home": "Bosnia and Herzegovina",
        "away": "Qatar",
        "homeScore": 3,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T19:00:00Z"
      }
    ],
    "D": [
      {
        "home": "USA",
        "away": "Paraguay",
        "homeScore": 4,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T01:00:00Z"
      },
      {
        "home": "Australia",
        "away": "Türkiye",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T04:00:00Z"
      },
      {
        "home": "USA",
        "away": "Australia",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T19:00:00Z"
      },
      {
        "home": "Türkiye",
        "away": "Paraguay",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T03:00:00Z"
      },
      {
        "home": "Türkiye",
        "away": "USA",
        "homeScore": 3,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T02:00:00Z"
      },
      {
        "home": "Paraguay",
        "away": "Australia",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T02:00:00Z"
      }
    ],
    "C": [
      {
        "home": "Brazil",
        "away": "Morocco",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-13T22:00:00Z"
      },
      {
        "home": "Haiti",
        "away": "Scotland",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T01:00:00Z"
      },
      {
        "home": "Scotland",
        "away": "Morocco",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-19T22:00:00Z"
      },
      {
        "home": "Brazil",
        "away": "Haiti",
        "homeScore": 3,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T00:30:00Z"
      },
      {
        "home": "Morocco",
        "away": "Haiti",
        "homeScore": 4,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T22:00:00Z"
      },
      {
        "home": "Scotland",
        "away": "Brazil",
        "homeScore": 0,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-24T22:00:00Z"
      }
    ],
    "E": [
      {
        "home": "Germany",
        "away": "Curaçao",
        "homeScore": 7,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T17:00:00Z"
      },
      {
        "home": "Côte d'Ivoire",
        "away": "Ecuador",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T23:00:00Z"
      },
      {
        "home": "Germany",
        "away": "Côte d'Ivoire",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T20:00:00Z"
      },
      {
        "home": "Ecuador",
        "away": "Curaçao",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T00:00:00Z"
      },
      {
        "home": "Ecuador",
        "away": "Germany",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T20:00:00Z"
      },
      {
        "home": "Curaçao",
        "away": "Côte d'Ivoire",
        "homeScore": 0,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T20:00:00Z"
      }
    ],
    "F": [
      {
        "home": "Netherlands",
        "away": "Japan",
        "homeScore": 2,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-14T20:00:00Z"
      },
      {
        "home": "Sweden",
        "away": "Tunisia",
        "homeScore": 5,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T02:00:00Z"
      },
      {
        "home": "Netherlands",
        "away": "Sweden",
        "homeScore": 5,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-20T17:00:00Z"
      },
      {
        "home": "Tunisia",
        "away": "Japan",
        "homeScore": 0,
        "awayScore": 4,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T04:00:00Z"
      },
      {
        "home": "Tunisia",
        "away": "Netherlands",
        "homeScore": 1,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T23:00:00Z"
      },
      {
        "home": "Japan",
        "away": "Sweden",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-25T23:00:00Z"
      }
    ],
    "H": [
      {
        "home": "Spain",
        "away": "Cabo Verde",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T16:00:00Z"
      },
      {
        "home": "Saudi Arabia",
        "away": "Uruguay",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T22:00:00Z"
      },
      {
        "home": "Spain",
        "away": "Saudi Arabia",
        "homeScore": 4,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T16:00:00Z"
      },
      {
        "home": "Uruguay",
        "away": "Cabo Verde",
        "homeScore": 2,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T22:00:00Z"
      },
      {
        "home": "Uruguay",
        "away": "Spain",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T00:00:00Z"
      },
      {
        "home": "Cabo Verde",
        "away": "Saudi Arabia",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T00:00:00Z"
      }
    ],
    "G": [
      {
        "home": "Belgium",
        "away": "Egypt",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-15T19:00:00Z"
      },
      {
        "home": "IR Iran",
        "away": "New Zealand",
        "homeScore": 2,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T01:00:00Z"
      },
      {
        "home": "Belgium",
        "away": "IR Iran",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-21T19:00:00Z"
      },
      {
        "home": "New Zealand",
        "away": "Egypt",
        "homeScore": 1,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T01:00:00Z"
      },
      {
        "home": "New Zealand",
        "away": "Belgium",
        "homeScore": 1,
        "awayScore": 5,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T03:00:00Z"
      },
      {
        "home": "Egypt",
        "away": "IR Iran",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T03:00:00Z"
      }
    ],
    "I": [
      {
        "home": "France",
        "away": "Senegal",
        "homeScore": 3,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T19:00:00Z"
      },
      {
        "home": "Iraq",
        "away": "Norway",
        "homeScore": 1,
        "awayScore": 4,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-16T22:00:00Z"
      },
      {
        "home": "France",
        "away": "Iraq",
        "homeScore": 3,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T21:00:00Z"
      },
      {
        "home": "Norway",
        "away": "Senegal",
        "homeScore": 3,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T00:00:00Z"
      },
      {
        "home": "Norway",
        "away": "France",
        "homeScore": 1,
        "awayScore": 4,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T19:00:00Z"
      },
      {
        "home": "Senegal",
        "away": "Iraq",
        "homeScore": 5,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-26T19:00:00Z"
      }
    ],
    "J": [
      {
        "home": "Argentina",
        "away": "Algeria",
        "homeScore": 3,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T01:00:00Z"
      },
      {
        "home": "Austria",
        "away": "Jordan",
        "homeScore": 3,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T04:00:00Z"
      },
      {
        "home": "Argentina",
        "away": "Austria",
        "homeScore": 2,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-22T17:00:00Z"
      },
      {
        "home": "Jordan",
        "away": "Algeria",
        "homeScore": 1,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T03:00:00Z"
      },
      {
        "home": "Jordan",
        "away": "Argentina",
        "homeScore": 1,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-28T02:00:00Z"
      },
      {
        "home": "Algeria",
        "away": "Austria",
        "homeScore": 3,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-28T02:00:00Z"
      }
    ],
    "K": [
      {
        "home": "Portugal",
        "away": "Congo DR",
        "homeScore": 1,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T17:00:00Z"
      },
      {
        "home": "Uzbekistan",
        "away": "Colombia",
        "homeScore": 1,
        "awayScore": 3,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-18T02:00:00Z"
      },
      {
        "home": "Portugal",
        "away": "Uzbekistan",
        "homeScore": 5,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T17:00:00Z"
      },
      {
        "home": "Colombia",
        "away": "Congo DR",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-24T02:00:00Z"
      },
      {
        "home": "Colombia",
        "away": "Portugal",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T23:30:00Z"
      },
      {
        "home": "Congo DR",
        "away": "Uzbekistan",
        "homeScore": 3,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T23:30:00Z"
      }
    ],
    "L": [
      {
        "home": "England",
        "away": "Croatia",
        "homeScore": 4,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T20:00:00Z"
      },
      {
        "home": "Ghana",
        "away": "Panama",
        "homeScore": 1,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 1,
        "date": "2026-06-17T23:00:00Z"
      },
      {
        "home": "England",
        "away": "Ghana",
        "homeScore": 0,
        "awayScore": 0,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T20:00:00Z"
      },
      {
        "home": "Panama",
        "away": "Croatia",
        "homeScore": 0,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 2,
        "date": "2026-06-23T23:00:00Z"
      },
      {
        "home": "Panama",
        "away": "England",
        "homeScore": 0,
        "awayScore": 2,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T21:00:00Z"
      },
      {
        "home": "Croatia",
        "away": "Ghana",
        "homeScore": 2,
        "awayScore": 1,
        "status": "FINISHED",
        "live": false,
        "matchday": 3,
        "date": "2026-06-27T21:00:00Z"
      }
    ]
  },
  "knockoutMatches": {
    "r32": [
      {
        "home": "South Africa",
        "away": "Canada",
        "homeScore": 0,
        "awayScore": 1,
        "winner": "Canada",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-28T19:00:00Z"
      },
      {
        "home": "Brazil",
        "away": "Japan",
        "homeScore": 2,
        "awayScore": 1,
        "winner": "Brazil",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-29T17:00:00Z"
      },
      {
        "home": "Germany",
        "away": "Paraguay",
        "homeScore": 4,
        "awayScore": 5,
        "winner": "Paraguay",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-29T20:30:00Z"
      },
      {
        "home": "Netherlands",
        "away": "Morocco",
        "homeScore": 3,
        "awayScore": 4,
        "winner": "Morocco",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-30T01:00:00Z"
      },
      {
        "home": "Côte d'Ivoire",
        "away": "Norway",
        "homeScore": 1,
        "awayScore": 2,
        "winner": "Norway",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-30T17:00:00Z"
      },
      {
        "home": "France",
        "away": "Sweden",
        "homeScore": 3,
        "awayScore": 0,
        "winner": "France",
        "status": "FINISHED",
        "live": false,
        "date": "2026-06-30T21:00:00Z"
      },
      {
        "home": "Mexico",
        "away": "Ecuador",
        "homeScore": 2,
        "awayScore": 0,
        "winner": "Mexico",
        "status": "FINISHED",
        "live": false,
        "date": "2026-07-01T02:00:00Z"
      },
      {
        "home": "England",
        "away": "Congo DR",
        "homeScore": 2,
        "awayScore": 1,
        "winner": "England",
        "status": "FINISHED",
        "live": false,
        "date": "2026-07-01T16:00:00Z"
      },
      {
        "home": "Belgium",
        "away": "Senegal",
        "homeScore": 3,
        "awayScore": 2,
        "winner": "Belgium",
        "status": "FINISHED",
        "live": false,
        "date": "2026-07-01T20:00:00Z"
      },
      {
        "home": "USA",
        "away": "Bosnia and Herzegovina",
        "homeScore": 2,
        "awayScore": 0,
        "winner": "USA",
        "status": "FINISHED",
        "live": false,
        "date": "2026-07-02T00:00:00Z"
      },
      {
        "home": "Spain",
        "away": "Austria",
        "homeScore": 3,
        "awayScore": 0,
        "winner": "Spain",
        "status": "FINISHED",
        "live": false,
        "date": "2026-07-02T19:00:00Z"
      },
      {
        "home": "Portugal",
        "away": "Croatia",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-02T23:00:00Z"
      },
      {
        "home": "Switzerland",
        "away": "Algeria",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-03T03:00:00Z"
      },
      {
        "home": "Australia",
        "away": "Egypt",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-03T18:00:00Z"
      },
      {
        "home": "Argentina",
        "away": "Cabo Verde",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-03T22:00:00Z"
      },
      {
        "home": "Colombia",
        "away": "Ghana",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-04T01:30:00Z"
      }
    ],
    "r16": [
      {
        "home": "Canada",
        "away": "Morocco",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-04T17:00:00Z"
      },
      {
        "home": "Paraguay",
        "away": "France",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-04T21:00:00Z"
      },
      {
        "home": "Brazil",
        "away": "Norway",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-05T20:00:00Z"
      },
      {
        "home": "Mexico",
        "away": "England",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-06T00:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-06T19:00:00Z"
      },
      {
        "home": "USA",
        "away": "Belgium",
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-07T00:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-07T16:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-07T20:00:00Z"
      }
    ],
    "qf": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-09T20:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-10T19:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-11T21:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-12T01:00:00Z"
      }
    ],
    "sf": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-14T19:00:00Z"
      },
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-15T19:00:00Z"
      }
    ],
    "final": [
      {
        "home": null,
        "away": null,
        "homeScore": null,
        "awayScore": null,
        "winner": "",
        "status": "TIMED",
        "live": false,
        "date": "2026-07-19T19:00:00Z"
      }
    ]
  }
};
